### ISSUE TITLE
Log Levels (discussion)

### ISSUE THREAD

**Issue by domenukk** [enowars/EnoELK#3]
Python has the following levels:
```   %(levelname)s       Text logging level for the message ("DEBUG", "INFO",
                        "WARNING", "ERROR", "CRITICAL")
```

Should we use thes or exchange `CRITICAL` with `FATAL`? 
I could not care less.
Do we even need to unify this?

**Comment by mauricesvp** [comment]
This can closed right? @Trolldemorted @domenukk
