### ISSUE TITLE
Standardize logging output of all enochecker variants

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/EnoELK#5]
We need
- a clear definition of all field names
- a severity that can be filtered easily in kibana (e.g. "give me everything above info")

**Comment by Trolldemorted** [comment]
@mauricesvp could you tackle this soonish?

**Comment by mauricesvp** [comment]
Just to get this right, [this](https://github.com/enowars/enochecker/blob/master/src/enochecker/logging.py) and [this](https://github.com/enowars/enochecker_async/blob/master/enochecker_async/enochecker.py) ELKFormatter should be the standardized?

**Comment by Trolldemorted** [comment]
You should define a standard, and then ensure that all log sources honor that standard. Log sources are enochecker, enochecker_async, EnoEngine, and EnoLauncher. enochecker_async's logging class is in enochecker_core, EnoEngine and EnoLauncher share the classes in the EnoCore.Logging namespace.

**Comment by Trolldemorted** [comment]
@Savallator an EnoLogMessage's method field should be nullable (?)

**Comment by mauricesvp** [comment]
Btw we need to update the [checker core](https://github.com/enowars/enochecker_core/blob/master/enochecker_core/__init__.py) too.

**Comment by Trolldemorted** [comment]
>Btw we need to update the checker core too.

I think you won't have to update enochecker_async, because enochecker_core handles the names internally.

> I just noticed that the async checker makes use of the checker core, the normal checker however doesn't ... 🤷

enochecker_core requires python3.7 or higher, and @domenukk built enochecker with support for older python versions.

**Comment by mauricesvp** [comment]
[The Engine](https://github.com/enowars/EnoEngine/blob/master/EnoCore/Models/Database/CheckerTask.cs) potentially needs to be updated aswell, if we want the same variable across all entities (not 100% necessary, but could be nice to tidy things up while we're at it).

**Comment by Trolldemorted** [comment]
yep, EnoEngine should now adhere to the specification
